version: '3.7'

services:
  web:
    build: .
    container_name: shopwave_web
    ports:
      - "8080:80"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: shopwave_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: shopwave_grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: shopwave_jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
